apiVersion: v1
kind: Service
metadata:
  name: usercreator
spec:
  selector:
    app: kubeusers
  ports:
    - port: 80
      targetPort: 8087
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercreator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: usercreator
  template:
    metadata:
      labels:
        app: usercreator
    spec:
      containers:
        - name: kubecontainers5
          image: manuforneri/usercreator:1.0.0
          ports:
            - containerPort: 8087
          imagePullPolicy: Always
